###
POST  http://localhost:9000/gimnasio/administradores/registroadmin HTTP/1.1
Content-Type: application/json

{
   "usuario": "admin2",
   "password": "admin@123"
}

###
POST  http://localhost:9000/gimnasio/administradores/loginadmin HTTP/1.1
Content-Type: application/json

{
   "usuario": "admin2",
   "password": "admin@123"
}

###
PUT  http://localhost:9000/gimnasio/administradores/actualizarpassword HTTP/1.1
Content-Type: application/json

{
   "usuario": "admin2",
   "password": "admin@123"
}