###
POST  http://localhost:9000/gimnasio/administradores/registroadmin HTTP/1.1
Content-Type: application/json

{
   "usuario": "admin2",
   "password": "admin@123"
}

###
POST  http://localhost:9000/gimnasio/administradores/loginadmin HTTP/1.1
Content-Type: application/json

{
   "id_administrador": 1,
   "usuario": "admin2",
   "contraseña": "admin@123"
}