# CONSULTAS DE LA TABLA CLIENTE

###
POST http://localhost:3001/clientes HTTP/1.1
Content-Type: application/json

{
   "id_cliente": 1,
   "nombre": "Paola",
   "apellidoPaterno": "Mayorga",
   "apellidoMaterno":"Aguirre",
   "numeroCelular": "9612502403",
   "fechaIncripcion": "2023-12-23"
}

###
PUT http://localhost:3001/clientes HTTP/1.1
Content-Type: application/json

{
   "id_cliente": 1,
   "nombre": "Paola",
   "apellidoPaterno": "Mayorga",
   "apellidoMaterno":"Aguirre",
   "numeroCelular": "9612502403",
   "fechaIncripcion": "2023-12-23"
}

###
GET http://localhost:3001/clientes HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3001/clientes/1 HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:3001/clientes/1 HTTP/1.1
Content-Type: application/json

