#CONSULTAS DE LA TABLA MENSUALIDADES

###
POST http://localhost:9000/gimnasio/mensualidades/registrar HTTP/1.1
Content-Type: application/json

{
    "id_mensualidades": 1,
    "id_cliente":1
}

###
PUT http://localhost:9000/gimnasio/mensualidades/modificar/1 HTTP/1.1
Content-Type: application/json

{
    "id_mensualidades": 1,
    "id_cliente":1
}

###
GET http://localhost:9000/gimnasio/mensualidades/obtenertodos HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:9000/gimnasio/mensualidades/eliminar/1 HTTP/1.1
Content-Type: application/json

//Prueba de consulta
###
POST http://localhost:9000/gimnasio/mensualidades/buscar HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "fecha": "2023-11-15"
}